<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Inventory\Commands\UpdateInventoryItem\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ShopVerse.BuildingBlocks\ShopVerse.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
