services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    ports:
      - "1435:1433"
    networks:
      - appnet
  finance-db:
    image: postgres:16
    container_name: finance-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FinanceDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
  messagebroker :
    image: rabbitmq:management
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet
  inventoryservice:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: InventoryService/Presentation/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=InventoryDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
      - MessageBroker__Host=amqp://messagebroker:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - sqlserver
      - messagebroker
    ports:
      - "5001:8080"
      - "5051:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - appnet

  salesservice:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: SalesService/Presentation/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
      - ConnectionStrings__Database=Server=sqlserver;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
      - GrpcSettings__InventoryUrl=http://inventory.grpc:8084
      - MessageBroker__Host=amqp://messagebroker:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - sqlserver
      - messagebroker
      - inventory.grpc
    ports:
      - "5056:8082"
      - "5055:8083"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - appnet

  inventory.grpc:
    image: ${DOCKER_REGISTRY-}inventorygrpc
    build:
      context: .
      dockerfile: InventoryService/Grpc/Inventory.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
      - ConnectionStrings__Database=Server=sqlserver;Database=InventoryDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "5292:8084"
      - "7198:8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - appnet

  productinventory.grpc:
    image: ${DOCKER_REGISTRY-}productinventorygrpc
    build:
      context: .
      dockerfile: InventoryService/Grpc/ProductInventory.Grpc/ProductInventory.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
      - ConnectionStrings__Database=Server=sqlserver;Database=InventoryDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
    ports:
      - "5294:8090"
      - "7242:8091"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - appnet

  finance.presentation:
    image: ${DOCKER_REGISTRY-}financepresentation
    build:
      context: .
      dockerfile: FinanceService/Presentation/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8086
      - ASPNETCORE_HTTPS_PORTS=8087
      - ConnectionStrings__Database=Host=finance-db;Port=5432;Database=FinanceDb;Username=postgres;Password=postgres
      - MessageBroker__Host=amqp://messagebroker:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - finance-db
      - messagebroker
    ports:
      - "5196:8086"
      - "5197:8087"
    networks:
      - appnet


  catalog.presentation:
    image: ${DOCKER_REGISTRY-}catalogpresentation
    build:
      context: .
      dockerfile: CatalogService/Catalog.Presentation/Catalog.Presentation/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8088
      - ASPNETCORE_HTTPS_PORTS=8089
      - ConnectionStrings__Database=Server=sqlserver;Database=CatalogDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
      - GrpcSettings__InventoryUrl=http://productinventory.grpc:8088
    depends_on:
      - sqlserver
      - productinventory.grpc
    ports:
      - "5234:8088"
      - "7288:8089"
    networks:
      - appnet
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
   


  identity.presentation:
    image: ${DOCKER_REGISTRY-}identitypresentation
    build:
      context: .
      dockerfile: IdentityService/Identity.Presentation/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8092
      - ASPNETCORE_HTTPS_PORTS=8093
      - ConnectionStrings__Database=Server=sqlserver;Database=IdentityDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "5203:8092"
      - "7118:8093"
    networks:
      - appnet
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  shopverse.identityserver.api:
    image: ${DOCKER_REGISTRY-}shopverseidentityserverapi
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer.Api/ShopVerse.IdentityServer.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8094
      - ASPNETCORE_HTTPS_PORTS=8095
      - ConnectionStrings__Database=Server=sqlserver;Database=IdentitySSODb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "5016:8094"
      - "7283:8095"
    networks:
      - appnet
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
networks:
  appnet:
    driver: bridge

volumes:
  pgdata:







